In [ ]:
import pandas as pd

df = pd.read_csv("data for embeddings.csv")

df.shape
df.dtypes

df.head(5)

,id,name,name_abbreviation,decision_date,docket_number,first_page,last_page,citations,volume,reporter,court,jurisdiction,last_updated,provenance,judges,parties,head_matter,word_count,char_count,text
0,10313299,"NEAL & COMPANY, INC., an Alaska corporation, A...",Neal & Co. v. City of Dillingham,1996-08-30,No. S-6525,89,96,923 P.2d 89,923,Pacific Reporter 2d,Alaska Supreme Court,Alaska,2021-08-10T16:59:37.070555+00:00,CAP,"Before RABINOWITZ, MATTHEWS, COMPTON and EASTA...","NEAL & COMPANY, INC., an Alaska corporation, A...","NEAL & COMPANY, INC., an Alaska corporation, A...",4144,25091,"OPINION\nRABINOWITZ, Justice.\nI. INTRODUCTION..."
1,10398651,"Major TOWNSEL, III, Appellant, v. STATE of Ala...",Townsel v. State,1988-11-04,No. A-1850,1353,1356,763 P.2d 1353,763,Pacific Reporter 2d,Alaska Court of Appeals,Alaska,2021-08-10T16:59:32.179770+00:00,CAP,"Before BRYNER, C.J., and COATS and SINGLETON, JJ.","Major TOWNSEL, III, Appellant, v. STATE of Ala...","Major TOWNSEL, III, Appellant, v. STATE of Ala...",1857,11480,"OPINION\nCOATS, Judge.\nMajor Townsel was conv..."
2,10398713,"George A. KONRAD, Appellant, v. STATE of Alask...",Konrad v. State,1988-11-10,No. A-2126,1369,1381,763 P.2d 1369,763,Pacific Reporter 2d,Alaska Court of Appeals,Alaska,2021-08-10T16:59:32.179770+00:00,CAP,"Before BRYNER, C.J., and COATS and SINGLETON, JJ.","George A. KONRAD, Appellant, v. STATE of Alask...","George A. KONRAD, Appellant, v. STATE of Alask...",6563,40790,"OPINION\nBRYNER, Chief Judge.\nGeorge A. Konra..."
3,10398665,"Richard D. ROBISON, Appellant, v. STATE of Ala...",Robison v. State,1988-11-04,No. A-2049,1357,1360,763 P.2d 1357,763,Pacific Reporter 2d,Alaska Court of Appeals,Alaska,2021-08-10T16:59:32.179770+00:00,CAP,"Before BRYNER, C.J., and COATS and SINGLETON, JJ.","Richard D. ROBISON, Appellant, v. STATE of Ala...","Richard D. ROBISON, Appellant, v. STATE of Ala...",2088,12493,"OPINION\nSINGLETON, Judge.\nA jury convicted R..."
4,10398692,"Darryl W. SLEDGE, Appellant, v. STATE of Alask...",Sledge v. State,1988-11-10,No. A-1892,1364,1369,763 P.2d 1364,763,Pacific Reporter 2d,Alaska Court of Appeals,Alaska,2021-08-10T16:59:32.179770+00:00,CAP,"Before BRYNER, C.J., and COATS and SINGLETON, JJ.","Darryl W. SLEDGE, Appellant, v. STATE of Alask...","Darryl W. SLEDGE, Appellant, v. STATE of Alask...",3529,20975,"OPINION\nSINGLETON, Judge.\nDarryl W. Sledge w..."

In [ ]:
import re

def clean_text(text):

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove extra spaces and newlines
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove non-alphanumeric characters (optional, adjust based on needs)
    text = re.sub(r'[^A-Za-z0-9\s.,;!?()"]', '', text)

    # Remove non-alphanumeric characters except punctuation
    text = re.sub(r'[^\w\s.,!?]', '', text)

    text = re.sub(r'\s+', ' ', text).strip()
    # Remove extra spaces and leading/trailing spaces

    text = re.sub(r'\d+', '<NUM>', text)
    # Replace numbers with a placeholder

    return text

In [ ]:
from tqdm import tqdm
tqdm.pandas()


df['cleaned_text'] = df['text'].progress_apply(clean_text)

100%|██████████| 100000/100000 [04:56<00:00, 337.48it/s]

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df.head(5)

         id  \
0  10313299
1  10398651
2  10398713
3  10398665
4  10398692

                                                                                                                     name  \
0  NEAL & COMPANY, INC., an Alaska corporation, Appellant, v. CITY OF DILLINGHAM and CH2M Hill Northwest, Inc., Appellees
1                                                             Major TOWNSEL, III, Appellant, v. STATE of Alaska, Appellee
2                                                               George A. KONRAD, Appellant, v. STATE of Alaska, Appellee
3                                                             Richard D. ROBISON, Appellant, v. STATE of Alaska, Appellee
4                                                               Darryl W. SLEDGE, Appellant, v. STATE of Alaska, Appellee

                  name_abbreviation decision_date docket_number first_page last_page  \
0  Neal & Co. v. City of Dillingham    1996-08-30    No. S-6525         89        96
1                  Townsel v. State    1988-11-04    No. A-1850       1353      1356
2                   Konrad v. State    1988-11-10    No. A-2126       1369      1381
3                  Robison v. State    1988-11-04    No. A-2049       1357      1360
4                   Sledge v. State    1988-11-10    No. A-1892       1364      1369

       citations  volume             reporter                    court jurisdiction  \
0    923 P.2d 89     923  Pacific Reporter 2d     Alaska Supreme Court       Alaska
1  763 P.2d 1353     763  Pacific Reporter 2d  Alaska Court of Appeals       Alaska
2  763 P.2d 1369     763  Pacific Reporter 2d  Alaska Court of Appeals       Alaska
3  763 P.2d 1357     763  Pacific Reporter 2d  Alaska Court of Appeals       Alaska
4  763 P.2d 1364     763  Pacific Reporter 2d  Alaska Court of Appeals       Alaska

                       last_updated provenance  \
0  2021-08-10T16:59:37.070555+00:00        CAP
1  2021-08-10T16:59:32.179770+00:00        CAP
2  2021-08-10T16:59:32.179770+00:00        CAP
3  2021-08-10T16:59:32.179770+00:00        CAP
4  2021-08-10T16:59:32.179770+00:00        CAP

                                                   judges  \
0  Before RABINOWITZ, MATTHEWS, COMPTON and EASTAUGH, JJ.
1       Before BRYNER, C.J., and COATS and SINGLETON, JJ.
2       Before BRYNER, C.J., and COATS and SINGLETON, JJ.
3       Before BRYNER, C.J., and COATS and SINGLETON, JJ.
4       Before BRYNER, C.J., and COATS and SINGLETON, JJ.

                                                                                                                   parties  \
0  NEAL & COMPANY, INC., an Alaska corporation, Appellant, v. CITY OF DILLINGHAM and CH2M Hill Northwest, Inc., Appellees.
1                                                             Major TOWNSEL, III, Appellant, v. STATE of Alaska, Appellee.
2                                                               George A. KONRAD, Appellant, v. STATE of Alaska, Appellee.
3                                                             Richard D. ROBISON, Appellant, v. STATE of Alaska, Appellee.
4                                                               Darryl W. SLEDGE, Appellant, v. STATE of Alaska, Appellee.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  head_matter  \
0  NEAL & COMPANY, INC., an Alaska corporation, Appellant, v. CITY OF DILLINGHAM and CH2M Hill Northwest, Inc., Appellees.\nNo. S-6525.\nSupreme Court of Alaska.\nAug. 30, 1996.\nR.R. De Young, Wade & De Young, Anchorage, for Appellant.\nR. Eldridge Hicks and Jeffrey S. Moeller, Hicks, Boyd, Chandler & Falconer, Anchorage, for Appellee City of Dillingham.\nD.K. “Kirby” Wright, Jr., Hintze • & Wright, Anchorage, for Appellee CH2M Hill Northwest, Inc.\nBefore RABINOWITZ, MATTHEWS, COMPTON and EASTAUGH, JJ.
1                                                                                          Major TOWNSEL, III, Appellant, v. STATE of Alaska, Appellee.\nNo. A-1850.\nCourt of Appeals of Alaska.\nNov. 4, 1988.\nMichael Dieni, Asst. Public Advocate, and Brant McGee, Public Advocate, Anchorage, for appellant.\nDavid Mannheimer, Asst. Atty. Gen., Office of Special Prosecutions and Appeals, Anchorage, and Grace Berg Schaible, Atty. Gen., Juneau, for appellee.\nBefore BRYNER, C.J., and COATS and SINGLETON, JJ.
2                                                                                                                                    George A. KONRAD, Appellant, v. STATE of Alaska, Appellee.\nNo. A-2126.\nCourt of Appeals of Alaska.\nNov. 10, 1988.\nJanet L. Crepps, Gilmore & Feldman, Anchorage, for appellant.\nCynthia M. Hora, Asst. Atty. Gen., Office of Sp. Prosecutions and Appeals, Anchorage, and Grace Berg Schaible, Atty. Gen., Juneau, for appellee.\nBefore BRYNER, C.J., and COATS and SINGLETON, JJ.
3                                                                                                    Richard D. ROBISON, Appellant, v. STATE of Alaska, Appellee.\nNo. A-2049.\nCourt of Appeals of Alaska.\nNov. 4, 1988.\nSusan Orlansky, Asst. Public Defender, and Dana Pabe, Public Defender, Anchorage, for appellant.\nNancy Simel, Asst. Atty. Gen., Office of Sp. Prosecutions and Appeals, Anchorage, and Grace Berg Schaible, Atty. Gen., Juneau, for appellee.\nBefore BRYNER, C.J., and COATS and SINGLETON, JJ.
4                                                                                                       Darryl W. SLEDGE, Appellant, v. STATE of Alaska, Appellee.\nNo. A-1892.\nCourt of Appeals of Alaska.\nNov. 10, 1988.\nBlair McCune, Asst. Public Defender, Dana Fabe, Public Defender, Anchorage, for appellant.\nRobert D. Bacon, Asst. Atty. Gen., Office of Sp. Prosecutions and Appeals, Anchorage, and Grace Berg Schaible, Atty. Gen., Juneau, for appellee.\nBefore BRYNER, C.J., and COATS and SINGLETON, JJ.

   word_count  char_count  \
0        4144       25091
1        1857       11480
2        6563       40790
3        2088       12493
4        3529       20975


In [ ]:
cleaned_data = df['cleaned_text']

In [ ]:
cleaned_data.to_csv('cleaned_data.csv', index=False)